### ISSUE TITLE
Errors occurring during testing

### ISSUE THREAD

**Issue by SherLockLi99** [yuantianyuan01/StreamMapNet#35]
Hello! When I enter the command to test, the following error occurs, what should I do to solve the following problem
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6020/6019, 19.2 task/s, elapsed: 313s, ETA:     0s
truncate 6019 samples from 6019
start evaluation!
len of the results 6019
saving submissions results to ./work_dirs/nusc_baseline_480_60x30_30e/submission_vector.json
collected 6019 samples in 0.55s
Traceback (most recent call last):
  File "/home/hwt/anaconda3/envs/streammapnet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 69, in build_from_cfg
    return obj_cls(**args)
  File "/home/hwt/network/StreamMapNet/plugin/datasets/nusc_dataset.py", line 28, in __init__
    super().__init__(**kwargs)
  File "/home/hwt/network/StreamMapNet/plugin/datasets/base_dataset.py", line 73, in __init__
    self._set_sequence_group_flag()
  File "/home/hwt/network/StreamMapNet/plugin/datasets/base_dataset.py", line 87, in _set_sequence_group_flag
    if self.samples[idx]['prev'] == -1:
KeyError: 'prev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/test.py", line 259, in <module>
    main()
  File "tools/test.py", line 255, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/home/hwt/network/StreamMapNet/plugin/datasets/base_dataset.py", line 233, in evaluate
    return self._evaluate(result_path, logger=logger)
  File "/home/hwt/network/StreamMapNet/plugin/datasets/base_dataset.py", line 236, in _evaluate
    self.evaluator = VectorEvaluate(self.eval_config)
  File "/home/hwt/network/StreamMapNet/plugin/datasets/evaluation/vector_eval.py", line 33, in __init__
    self.dataset = build_dataset(dataset_cfg)
  File "/home/hwt/network/StreamMapNet/mmdetection3d/mmdet3d/datasets/builder.py", line 46, in build_dataset
    dataset = build_from_cfg(cfg, MMDET_DATASETS, default_args)
  File "/home/hwt/anaconda3/envs/streammapnet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "NuscDataset: 'prev'"

**Comment by yuantianyuan01** [comment]
Hi, did you use our data converter to generate the annotation files?

**Comment by SherLockLi99** [comment]
> Hi, did you use our data converter to generate the annotation files?

I've generated a new annotation file, but I'm testing the model under the old split

**Comment by Chouaib-b** [comment]
I bumped by the same issue when running the test file or the "test dataset"
I think the data converter doesn't support the new split for the test data set See Lines 148-173  in `tools/data_converter/nuscenes_converter.py`
